routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;






Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
/* Route::get('/usuarios', 'UserController@index'); */

Route::resource('usuarios', 'UserController');/* ->middleware('auth'); */
/* Route::get('/clientes', function () {
    return view('clientes.index');
}); */

Route::resource('roles', 'RoleController');



Route::get('clientes', 'ClientestController@Index')->name('clientes.index');
Route::resource('clientes', 'ClientesController');
Route::match(['put', 'patch'], 'clientes/{id}','ClientesController@update')->name('clientes.update');
Route::delete('clientes/{id}','ClientesController@destroy')->name('clientes.destroy');


Route::get('Categorias', 'CategoriasController@index')->name('Categorias.index');
Route::resource('Categorias', 'CategoriasController');
Route::match(['put', 'patch'], 'Categorias/{id}','CategoriasController@update')->name('Categorias.update');
Route::delete('Categorias/{id}','CategoriasController@destroy')->name('Categorias.destroy');


//routes para la muestra de seleccion de Notas
Route::resource('/notas/todas', 'NotasController');
Route::get('/notas/favoritas', 'NotasController@favoritas');
Route::get('/notas/archivadas', 'NotasController@archivadas');

//productos
Route::get('productos', 'ControladorProductos@index')->name('productos.index');

Route::get('productos/crear', 'ControladorProductos@create')->name('productos.create');

Route::post('productos', 'ControladorProductos@store')->name('productos.store');

Route::get('productos/{producto}/editar', 'ControladorProductos@edit')->name('productos.edit');

Route::match(['put', 'patch'], 'productos/{producto}/editar', 'ControladorProductos@update')->name('productos.update');

Route::delete('producto/{producto}', 'ControladorProductos@destroy')->name('productos.destroy');
Auth::routes();

Route::get('productos/verpdf', 'ControladorProductos@verpdf')->name('productos.verpdf');




//Entradas
Route::get('Entradas', 'ControladorEntradas@index')->name('entradas.index');

Route::get('Entradas/crear', 'ControladorEntradas@create')->name('Entradas.create');

Route::post('Entradas', 'ControladorEntradas@store')->name('Entradas.store');

Route::get('Entradas/{entrada}/editar', 'ControladorEntradas@edit')->name('Entradas.edit');

Route::match(['put', 'patch'], 'Entradas/{entrada}/editar', 'ControladorEntradas@update')->name('Entradas.update');

Route::delete('Entradas/{entrada}', 'ControladorEntradas@destroy')->name('Entradas.destroy');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('Entradas/{entrada}/detalle', 'ControladorEntradas@detail')->name('Entradas.detail');

// Detalle Entradas

Route::get('detalleEntrada', 'ControladorDetalleEntrada@index')->name('detalleEntrada.index');


 // Datalle Proveedores

Route::get('proveedores', 'ControladorProveedores@index')->name('proveedores.index');

Route::get('proveedores/crear', 'ControladorProveedores@create')->name('proveedores.create');

Route::post('proveedores', 'ControladorProveedores@store')->name('proveedores.store');

Route::get('proveedores/{proveedor}/editar', 'ControladorProveedores@edit')->name('proveedores.edit');

Route::match(['put', 'patch'], 'proveedores/{proveedor}/editar', 'ControladorProveedores@update')->name('proveedores.update');

Route::delete('proveedor/{proveedor}', 'ControladorProveedores@destroy')->name('proveedores.destroy');
Auth::routes();

resources/views/usuarios/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Msmarketing | Crear usuario</title>

</head>

<body>
    @extends('layouts.app')

    @section('content')


    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2>Registrar usuario</h2>

            </div>
        </div>

        <form action="{{url('/usuarios')}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field()}}


            <div class="row">
                <div class="form-group col-md-6">
                    <label>Nombre</label>
                    <input type="text" name="name" class="form-control {{$errors->has('name')?'is-invalid':('')}}"  placeholder="Nombre"
                    value="{{isset($user->name)?$user->name:old('name')}}">
                    {!! $errors->first('name', '<div class="invalid-feedback">El campo nombre es obligatorio y debe tener min 6 caracteres</div>')!!}


                </div>
                <div class="form-group col-md-6">
                    <label>Email</label>
                    <input type="email" value="{{isset($user->email)?$user->name:old('email')}}"  class="form-control {{$errors->has('email')?'is-invalid':('')}} "    name="email" placeholder="Email">
                    {!! $errors->first('email', '<div class="invalid-feedback">El campo email es obligatorio</div>')!!}

                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label>Contraseña</label>
                    <input type="password"   name="password"  value="{{isset($user->password)?$user->name:old('password')}}"     class="form-control {{$errors->has('password')?'is-invalid':('')}}"  placeholder="Contraseña">
                    {!! $errors->first('password', '<div class="invalid-feedback">El campo password es obligatorio debe contener al menos 6 caracteres.</div>')!!}
                </div>
                <div class="form-group col-md-6">
                    <label>Confirmar contraseña</label>
                    <input type="password" name="password_confirmation" class="form-control {{$errors->has('password_confirmation')?'is-invalid':('')}}"  placeholder="Confirmar contraseña">
                    {!! $errors->first('password_confirmation', '<div class="invalid-feedback">El campo password es obligatorio debe contener al menos 6 caracteres.</div>')!!}

                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label>Rol</label>
                    <select name="rol"  class="form-control {{$errors->has('rol')?'is-invalid':('')}}">
                        <option selected disabled>Elige un rol para este usuario</option>
                        @foreach($roles as $role )
                        <option value="{{$role->id}}">{{$role->name}}</option>
                        @endforeach
                    </select>
                    {!! $errors->first('rol', '<div class="invalid-feedback">El campo rol es obligatorio</div>')!!}


                </div>
                <div class="form-group col-md-6">
                    <label> Imagen</label>
                    <input type="file"  class="form-control {{$errors->has('imagen')?'is-invalid':''}}" name="imagen" class="form-control" type="file">
                    {!! $errors->first('imagen', '<div class="invalid-feedback">El campo imagen es obligatorio</div>')!!}

                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <button type="submit" class="btn btn-primary">Guardar usuario</button>
                    <button type="reset" class="btn btn-danger">Borrar Campos</button>
                    <a href="{{url('usuarios')}}" class="btn btn-primary">Regresar</a>
                </div>
            </div>
        </form>

    </div>



    @endsection


</body>

</html>

resources/views/usuarios/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Msmarketing | Modificar usuario</title>

</head>

<body>
@extends('layouts.app')

@section('content')

<div class="container">
        <div class="row">
            <div class="col-sm-6">
            <h2>Editar usuario {{$user->name}}</h2>
                @if ($errors->any())


                @endif
            </div>
        </div>





    <form action="{{ route ('usuarios.update', $user->id) }}" method="POST" enctype="multipart/form-data">
        @method('PATCH')
        {{ csrf_field()}}

        <div class="row">
            <div class="form-group col-md-6">
                <label>Nombre</label>
                <input type="text" name="name" class="form-control {{$errors->has('name')?'is-invalid':('')}}"  placeholder="Nombre"
                    value="{{isset($user->name)?$user->name:old('name')}}">
                    {!! $errors->first('name', '<div class="invalid-feedback">El campo nombre es obligatorio y debe tener min 6 caracteres</div>')!!}


            </div>
            <div class="form-group col-md-6">
                <label>Email</label>
                <input type="email" class="form-control {{$errors->has('email')?'is-invalid':('')}} " value="{{$user->email}}" name="email" placeholder="Email">
                {!! $errors->first('email', '<div class="invalid-feedback">El campo email es obligatorio</div>')!!}




            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <label>Contraseña <span class="small">(Opcional)</span></label>
                <input type="password" name="password" class="form-control" placeholder="Contraseña">
            </div>
            <div class="form-group col-md-6">
                <label>Confirmar contraseña<span class="small">(Opcional)</span></label>
                <input type="password" class="form-control" name="password_confirmation" placeholder="Confirmar contraseña">
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <label>Rol</label>
                <select name="rol" class="form-control">
                    <option selected disabled>Elige un rol para este usuario</option>
                    @foreach($roles as $role )
                    @if($role->name == str_replace(array( '["','"]'),'', $user->tieneRol()))
                    <option value="{{$role->id}}" selected>{{$role->name}}</option>


                    @else
                    <option value="{{$role->id}}">{{$role->name}}</option>

                    @endif

                    @endforeach
                </select>

            </div>
            <div class="form-group col-md-6">
                <label> Imagen</label>
                <input type="file" name="imagen" class="form-control">
                @if($user->imagen != "")
                <img src="{{asset  ('imagenes/'.$user->imagen) }}" alt="{{ $user->imagen }}" height="50px" width="50px">
                @endif
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-6">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <button type="reset" class="btn btn-danger">Borrar Campos</button>
                 <a href="{{url('usuarios')}}" class="btn btn-primary">regresar</a>
            </div>
        </div>
    </form>
</div>
</div>
</div>



@endsection

</body>
</html>

resources/views/usuarios/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Msmarketing | Usuarios</title>

</head>

<body>
@extends('layouts.app')

@section('content')
@csrf
<div class="container">
    <h2>Lista de usuarios registardos <a href="usuarios/create"><button type="button" class="btn btn-success float-right ">Agregar usuario</button></a></h2>

    <h6>
        @if($search)
        <div class="alert alert-primary" role="alert">
            los resultados para tu busqueda '{{$search}}' son:
        </div>
        @endif
    </h6>




    <table class="table table-light table-hover">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Correo electrónico</th>
                <th scope="col">Tipo de rol</th>
                <th scope="col">Imagen</th>
                <th scope="col">Opciones</th>

            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>
                    @foreach($user->roles as $role)
                    {{$role->name}}
                    @endforeach
                </td>
                <td>
                    <img src="{{asset('imagenes/'.$user->imagen) }}" alt="{{ $user->imagen }}" height="50px" width="50px">
                </td>
                <td>

                    <form action="{{route('usuarios.destroy', $user->id)}}" method="POST">
                        <a href="{{ route('usuarios.show', $user->id)}}"><button type="button" class="btn btn-secondary  btn-sm"><i class="fas fa-eye"></i></button></a>
                        <a href="{{ route('usuarios.edit', $user->id) }}"><button type="button" class="btn btn-primary btn-sm"><i class="fas fa-user-edit"></i></button></a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                </td>
                </form>

            </tr>

            @endforeach

        </tbody>
    </table>
    <!-- aca estamos recoriendo los usuarios en un forma de lista por paginas -->

    {{ $users->links() }}
</div>



@endsection
</body>
</html>

resources/views/usuarios/show.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Msmarketing | Vista - Usuarios</title>

</head>

<body>
@extends('layouts.app')

@section('content')


<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">{{$user->name}}</h1>
        <p class="lead">{{$user->email}}</p>
    </div>
</div>




@endsection
</body>
</html>